### ISSUE TITLE
openapi version 

### ISSUE THREAD

**Issue by darduf** [snok/drf-openapi-tester#271]
Hi 

I have an openapi yaml of version 3.0.1. When I run `SchemaTester` I get the following failure.

```
  File "/../venv/lib/python3.9/site-packages/openapi_spec_validator/validation/validators.py", line 75, in validate
    raise err
openapi_spec_validator.validation.exceptions.OpenAPIValidationError: '3.0.1' does not match '^3\\.1\\.\\d+(-.+)?$'

Failed validating 'pattern' in schema['properties']['openapi']:
    {'pattern': '^3\\.1\\.\\d+(-.+)?$', 'type': 'string'}

On instance['openapi']:
    '3.0.1' 
```

The validator doesn't seem to be picking up that this openapi is of version 3.0.#. 
Looking through traceback, it appears that `openapi_v31_spec_validator` is the set/default validator. 
Is it possible to override/address this so it uses `openapi_v30_schema_validator`

**Comment by sondrelg** [comment]
Do you think more granular logic here might solve this? https://github.com/snok/drf-openapi-tester/blob/dacbf6cec0439afb522c6bd48ca24ed0a02bc1a8/openapi_tester/loaders.py#L99

**Comment by darduf** [comment]
> Do you think more granular logic here might solve this?

I think so, how about a regex pattern match on the `openapi` value  here to decide on what schema validator to use?

**Comment by sondrelg** [comment]
Sounds sensible to me. Are you able to create a PR?

**Comment by darduf** [comment]
I don't have bandwidth right now, but I will try to get a PR in soon. Thanks

**Comment by sondrelg** [comment]
Version 2.1.2 should be released now. Would you mind testing it when you get a chance @darduf?

**Comment by darduf** [comment]
Updated 2.1.2 - this OAS validator is working for me now.

**Comment by sondrelg** [comment]
Great, thanks again!
