### ISSUE TITLE
Requested djangorestframework version inferior than the latest

### ISSUE THREAD

**Issue by eloi-martinez-qida** [snok/drf-openapi-tester#278]
The conflict is caused by:
The user requested djangorestframework==3.14.0
drf-openapi-tester 2.1.2 depends on djangorestframework<3.14.0

**Comment by JonasKs** [comment]
Seems to have been implemented [here.](https://github.com/snok/drf-openapi-tester/commit/87864ba35b3de15cde86d8e4150ab20bf57bce34) 

I don’t believe that was intentional, @sondrelg? I’d assume not, so PR to fix it is welcome. 😊

**Comment by sondrelg** [comment]
Actually, it was done on purpose as the latest version of DRF did not work for `drf-yasg` latest (see https://github.com/axnsan12/drf-yasg/issues/810). But that seems resolved now, so I'll see if I can release a new patch release which resolves this 🙂

**Comment by sondrelg** [comment]
Version 2.1.3 is out now which resolves this @eloi-martinez-qida 🙂 Please let me know if it doesn't fix your issue 🙏

**Comment by eloi-martinez-qida** [comment]
Yes, that fixed the issue, thanks!!
