### ISSUE TITLE
Support for path prefix

### ISSUE THREAD

**Issue by petkostas** [snok/drf-openapi-tester#281]
Our API prefix is included in the server part of the OAS files to remove repetition from endpoints. It would be nice to support specifying the prefix while initializing the schema tester:

```python
from openapi_tester import SchemaTester

schema_tester = SchemaTester(schema_file_path="./openapi.yaml", prefix="/api/v2")
```

**Comment by sondrelg** [comment]
I think this sounds like a good idea without any real drawbacks. If you want to open a PR adding this feature, I would be happy to accept it 🙂

**Comment by petkostas** [comment]
@sondrelg, thanks for the fast response! I will do so

**Comment by sondrelg** [comment]
I will close this in the meantime :+1: Ping me when the PR is ready and I'll review :slightly_smiling_face:
