### ISSUE TITLE
Test response validation logic on the `file` schema type.

### ISSUE THREAD

**Issue by sondrelg** [snok/drf-openapi-tester#42]
Swagger 2.0 has a special `file` type, which resembles the string type: https://swagger.io/docs/specification/data-models/data-types/#file

The current response validation check for a file type is the same as a regular string:

```python
if not isinstance(data, str) and data is not None:
    raise format_error(error_message=f'Mismatched types.', data=data, schema=schema, parent=parent)
```

We need to test this logic with a real example.

**Comment by Goldziher** [comment]
no longer relevant as such
